export const expenseDetails: ExpenseDetails = {
  familyHarvest: [
    { item: 'Big Card Laminated Envelops', planned: 47000, actual: 45000 },
    { item: 'Small Envelops', planned: 18000, actual: 20000 },
  ],
  childrenHarvest: [
    { item: 'Chicken (2 cartons)', planned: 104000, actual: 78000 },
    { item: 'Rice (Bag)', planned: 50000, actual: 30000 },
    { item: 'Pepper & Spices', planned: 42000, actual: 47100 },
    { item: 'Groundnut Oil', planned: 13000, actual: 13000 },
    { item: 'Soft drink and water (1 pack each)', planned: 0, actual: 5000 },
    {
      item: 'Sweets (4 Packs)',
      planned: 20000,
      actual: 16800,
      id: 'packs',
    },
    {
      item: 'Coolers',
      planned: 30000,
      actual: 25500,
      id: 'packs',
      note: 'Packs for Chairmen and Chairpersons',
    },
    {
      item: 'Takeaway (General Packs)',
      planned: 24000,
      actual: 11000,
      id: 'packs',
    },
    {
      item: 'Biscuit (3 Cartoons)',
      planned: 10000,
      actual: 9600,
      id: 'packs',
    },
    {
      item: 'Waterbottles',
      planned: 10000,
      actual: 8400,
      id: 'packs',
      note: 'Packs for Chairmen and Chairpersons',
    },
    {
      item: '1 Cartoon of Indomie',
      planned: 11000,
      actual: 8000,
      id: 'packs',
    },
    {
      item: 'Ballons & Ribbons',
      planned: 15000,
      actual: 8000,
      id: 'packs',
    },
    {
      item: 'Bags/Nylons (To pack foods)',
      planned: 20000,
      actual: 8400,
      id: 'packs',
    },
    {
      item: 'Transport fare',
      planned: 7000,
      actual: 6200,
      id: 'packs',
    },
    {
      item: 'Long Sweets',
      planned: 4000,
      actual: 3300,
      id: 'packs',
    },
    {
      item: 'Chinchin, Biros and Pencils',
      planned: 3000,
      actual: 3000,
      id: 'packs',
    },
    {
      item: 'POS Charges',
      planned: 0,
      actual: 1500,
      id: 'packs',
    },
    {
      item: 'Spoons',
      planned: 2000,
      actual: 800,
      id: 'packs',
    },
    {
      item: 'Big Sack Bag',
      planned: 0,
      actual: 700,
      id: 'packs',
    },
    { item: 'Gas 10 Kg', planned: 21600, actual: 10000 },
    {
      item: 'Drinks (5 packs)',
      planned: 39000,
      actual: 0,
      note: 'Donated by Mummy Oluwunmi',
      id: 'donations',
    },
    {
      item: 'Water (5 packs)',
      planned: 22000,
      actual: 0,
      note: 'Donated by Mummy Oluwunmi',
      id: 'donations',
    },
    {
      item: '1 Cartoon of Biscuit',
      planned: 0,
      actual: 0,
      note: 'Donated by Mummy Bolu',
      id: 'donations',
    },
    {
      item: '1 Cartoon of Mr Fruit',
      planned: 0,
      actual: 0,
      note: 'Donated by Mummy Bolu',
      id: 'donations',
    },
    {
      item: 'Burner',
      planned: 10000,
      actual: 0,
      note: 'Donated by Baba Emma Wife',
      id: 'donations',
    },
    {
      item: 'Pots',
      planned: 5000,
      actual: 0,
      note: 'Donated by Mama Dangote',
      id: 'donations',
    },
    {
      item: 'Logistics',
      planned: 17200,
      actual: 17200,
      note: 'Ile Epo TP = 6,900 | Utensil TP = 1,000 | Ile Epo POS Charges = 1,600 | Extral Nylon = 3,200 | Engin Oil = 3,500',
    },
  ],
  praiseNight: [
    { item: 'Flour (3 Paints)', planned: 13500, actual: 12000 },
    { item: 'Sugar, Yeast & Charges', planned: 7000, actual: 12000 },
    { item: 'Drinks', planned: 20000, actual: 29850 },
    { item: 'Chair', planned: 0, actual: 4000 },
    {
      item: 'Praise Night Instrumentalist',
      planned: 0,
      actual: 20000,
    },
  ],
  dedicationLogistics: [
    { item: 'Thanksgiving Fund', planned: 200000, actual: 0 },
    { item: 'Cap and Gardle', planned: 350000, actual: 175000 },
    { item: 'Programs (200 Copies)', planned: 200000, actual: 220000 },
    { item: 'Instruments (Sound, Mic)', planned: 100000, actual: 0 },
    { item: 'Fuel 110 Liters @ 1,000', planned: 110000, actual: 10000 },
    {
      item: '2 Banners (Harvest and Red carpet)',
      planned: 40000,
      actual: 47000,
    },
    { item: 'Revival Banner (3x4)', planned: 0, actual: 7000 },
    { item: 'All Guests Card Printing', planned: 0, actual: 5000 },
    { item: 'Ink for Printer', planned: 10000, actual: 12000 },
    { item: 'Logistics (Transport)', planned: 100000, actual: 0 },
    { item: 'Fruits', planned: 100000, actual: 0 },
    { item: 'Decoration', planned: 100000, actual: 0 },
    { item: 'Cake', planned: 50000, actual: 0 },
    { item: 'Ballons & Ribbons', planned: 20000, actual: 0 },
    { item: 'Chairs and Canopy', planned: 30000, actual: 0 },
    { item: 'Towels (2 Dozens)', planned: 22500, actual: 21500 },
    { item: 'Small Card Envelops (50 Copies)', planned: 15000, actual: 15000 },
    {
      item: 'Small Normal Envelops (600 Copies)',
      planned: 25000,
      actual: 50000,
    },
    { item: 'Handbill (100 copies)', planned: 15000, actual: 15000 },
    { item: 'ATM Card (Committee Account)', planned: 2500, actual: 2500 },
    { item: 'CAC Registration', planned: 19000, actual: 19000 },
    {
      item: 'Correction on Envelop',
      planned: 6000,
      actual: 0,
      note: 'Refund by church',
    },
    { item: 'Receipt', planned: 12000, actual: 12000 },
    { item: 'Printing on Towel (2 Dozens)', planned: 3000, actual: 3000 },
    { item: 'Invitation to King', planned: 10500, actual: 10500 },
    { item: 'Reminder to King', planned: 0, actual: 2500 },
    { item: 'Invitation to Bale Lafenwa', planned: 3500, actual: 3500 },
    {
      item: 'Choir Overnight Rehearsal Refreshment (24-10-25)',
      planned: 0,
      actual: 3200,
    },
    {
      item: 'TP to distribute Praise night envelop and reminder letters',
      planned: 0,
      actual: 7000,
    },
    { item: 'TP to HQ and Ikotun (Programme)', planned: 0, actual: 7500 },
    {
      item: 'Fixing of 2 Talking Drumes (Praise Night & Sunday Service',
      planned: 0,
      actual: 15000,
    },
    { item: 'Mic batteries', planned: 0, actual: 10000 },
    { item: 'Erecting of harvest banner', planned: 0, actual: 5000 },
    { item: 'Preacher on 1 Nov 25 (Sunday)', planned: 0, actual: 11600 },
    { item: 'Rivivalist on 5 Nov 25 (Shilo)', planned: 0, actual: 2500 },
    { item: 'Rivivalist on 5 Nov 25 (Shilo)', planned: 0, actual: 2500 },
    { item: 'Keyboard', planned: 0, actual: 17000 },
    { item: 'Conductor', planned: 0, actual: 10000 },
    {
      item: 'Choir Overnight Rehearsal Refreshment (24-11-05)',
      planned: 0,
      actual: 10600,
    },
    {
      item: 'Bulb and Wire',
      planned: 0,
      actual: 5500,
    },
    { item: 'Guests Ribbon', planned: 0, actual: 40000 },
    { item: 'Committee Ribbon', planned: 0, actual: 30000 },
    { item: 'Committee Printing', planned: 0, actual: 17000 },
    { item: 'Chair renting', planned: 0, actual: 34000 },
  ],
  dedicationEntertainment: [
    { item: 'Cow (2)', planned: 1500000, actual: 200000, note: 'Balanced by church' },
    {
      item: 'Rice (3 Bags)',
      planned: 240000,
      actual: 30000,
      note: 'Half bag of rice in store',
    },
    {
      item: '1 Bag of rice',
      planned: 0,
      actual: 0,
      id: 'donations',
      note: "Donated buy Iya Shehu's daughter",
    },
    {
      item: 'Bottle Water (50 Packs)',
      planned: 65000,
      actual: 0,
      id: 'donations',
      note: '20 packs donated by Mummy Oluwunmi',
    },
    {
      item: 'Big Soft Drinks (50 Packs)',
      planned: 210000,
      actual: 0,
      id: 'donations',
      note: '20 packs donated by Mummy Oluwunmi',
    },
    { item: 'Small Soft Drinks (17 Packs)', planned: 48000, actual: 0 },
    { item: 'Pepper, Onions, Fruits and Transport', planned: 200000, actual: 225000 },
    { item: 'Groundnut Oil (25L x 2)', planned: 120000, actual: 0 },
    { item: 'Tin Tomatoes x 4 @ 15,000', planned: 60000, actual: 0 },
    { item: 'Gas (12kg Cylinders x 3)', planned: 43500, actual: 63200 },
    { item: 'Gas Burner', planned: 5000, actual: 5000 },
    { item: 'Cooking Pot (Large x 3)', planned: 10000, actual: 2500 },
    {
      item: 'Coolers for Spritual/Royal guest (3 dozens)',
      planned: 150000,
      actual: 111600,
      id: 'packs',
    },
    {
      item: 'Boul for special guests and committee (6 dozens)',
      planned: 0,
      actual: 64800,
      id: 'packs',
    },
    {
      item: 'General takeaway packs (400 pieces) adult',
      planned: 0,
      actual: 42000,
      id: 'packs',
    },
    {
      item: 'General takeaway packs (200 pieces) children',
      planned: 0,
      actual: 18000,
      id: 'packs',
    },
    {
      item: 'White nylons for adult general packs',
      planned: 0,
      actual: 35000,
      id: 'packs',
    },
    {
      item: 'White nylons for children general packs',
      planned: 0,
      actual: 12000,
      id: 'packs',
    },
    {
      item: 'Bags for Spritual/Royal guest (3 dozens)',
      planned: 0,
      actual: 14400,
      id: 'packs',
    },
    {
      item: 'Bags for special guests (4 1/2 dozens)',
      planned: 0,
      actual: 19800,
      id: 'packs',
    },
    {
      item: 'Bags for Prophets (2 dozens)',
      planned: 0,
      actual: 7600,
      id: 'packs',
    },
    {
      item: 'Bags for Committee (1 1/2 dozen)',
      planned: 0,
      actual: 6750,
      id: 'packs',
    },
    {
      item: 'Small plastic spoons (700 pieces)',
      planned: 0,
      actual: 4550,
      id: 'packs',
    },
    {
      item: 'Big sack',
      planned: 0,
      actual: 2000,
      id: 'packs',
    },
    {
      item: 'Rubber band',
      planned: 0,
      actual: 1500,
      id: 'packs',
    },
    {
      item: 'Money for those that pack coolers',
      planned: 0,
      actual: 1000,
      id: 'packs',
    },
    {
      item: 'Money for those that carry load',
      planned: 0,
      actual: 1000,
      id: 'packs',
    },
    {
      item: 'TP & charges',
      planned: 0,
      actual: 15500,
      id: 'packs',
    },
    { item: 'Cow slaughtering', planned: 0, actual: 30000 },
    { item: 'Transport to pack drinks', planned: 0, actual: 3000 },
    { item: 'Capentering 8-11-25', planned: 0, actual: 1000 },
    { item: 'Pure water for children', planned: 0, actual: 2000 },

  ],
};
