export const expenseDetails: ExpenseDetails = {
  familyHarvest: [
    { item: 'Big Card Laminated Envelops', planned: 47000, actual: 45000 },
    { item: 'Small Envelops', planned: 18000, actual: 20000 },
  ],
  childrenHarvest: [
    { item: 'Chicken (2 cartons)', planned: 104000, actual: 78000 },
    { item: 'Rice (Bag)', planned: 50000, actual: 30000 },
    { item: 'Pepper & Spices', planned: 42000, actual: 47100 },
    { item: 'Groundnut Oil', planned: 13000, actual: 13000 },
    { item: 'Soft drink and water (1 pack each)', planned: 0, actual: 5000 },
    {
      item: 'Sweets (4 Packs)',
      planned: 20000,
      actual: 16800,
      id: 'packs',
    },
    {
      item: 'Coolers',
      planned: 30000,
      actual: 25500,
      id: 'packs',
      note: 'Packs for Chairmen and Chairpersons',
    },
    {
      item: 'Takeaway (General Packs)',
      planned: 24000,
      actual: 11000,
      id: 'packs',
    },
    {
      item: 'Biscuit (3 Cartoons)',
      planned: 10000,
      actual: 9600,
      id: 'packs',
    },
    {
      item: 'Waterbottles',
      planned: 10000,
      actual: 8400,
      id: 'packs',
      note: 'Packs for Chairmen and Chairpersons',
    },
    {
      item: '1 Cartoon of Indomie',
      planned: 11000,
      actual: 8000,
      id: 'packs',
    },
    {
      item: 'Ballons & Ribbons',
      planned: 15000,
      actual: 8000,
      id: 'packs',
    },
    {
      item: 'Bags/Nylons (To pack foods)',
      planned: 20000,
      actual: 8400,
      id: 'packs',
    },
    {
      item: 'Transport fare',
      planned: 7000,
      actual: 6200,
      id: 'packs',
    },
    {
      item: 'Long Sweets',
      planned: 4000,
      actual: 3300,
      id: 'packs',
    },
    {
      item: 'Chinchin, Biros and Pencils',
      planned: 3000,
      actual: 3000,
      id: 'packs',
    },
    {
      item: 'POS Charges',
      planned: 0,
      actual: 1500,
      id: 'packs',
    },
    {
      item: 'Spoons',
      planned: 2000,
      actual: 800,
      id: 'packs',
    },
    {
      item: 'Big Sack Bag',
      planned: 0,
      actual: 700,
      id: 'packs',
    },
    { item: 'Gas 10 Kg', planned: 21600, actual: 10000 },
    {
      item: 'Drinks (5 packs)',
      planned: 39000,
      actual: 0,
      note: 'Donated by Mummy Oluwunmi',
      id: 'donations',
    },
    {
      item: 'Water (5 packs)',
      planned: 22000,
      actual: 0,
      note: 'Donated by Mummy Oluwunmi',
      id: 'donations',
    },
    {
      item: '1 Cartoon of Biscuit',
      planned: 0,
      actual: 0,
      note: 'Donated by Mummy Bolu',
      id: 'donations',
    },
    {
      item: '1 Cartoon of Mr Fruit',
      planned: 0,
      actual: 0,
      note: 'Donated by Mummy Bolu',
      id: 'donations',
    },
    {
      item: 'Burner',
      planned: 10000,
      actual: 0,
      note: 'Donated by Baba Emma Wife',
      id: 'donations',
    },
    {
      item: 'Pots',
      planned: 5000,
      actual: 0,
      note: 'Donated by Mama Dangote',
      id: 'donations',
    },
    {
      item: 'Logistics',
      planned: 17200,
      actual: 17200,
      note: 'Ile Epo TP = 6,900 | Utensil TP = 1,000 | Ile Epo POS Charges = 1,600 | Extral Nylon = 3,200 | Engin Oil = 3,500',
    },
  ],
  praiseNight: [
    { item: 'Flour (3 Paints)', planned: 13500, actual: 0 },
    { item: 'Groundnut Oil', planned: 12000, actual: 0 },
    { item: 'Sugar', planned: 7000, actual: 0 },
    { item: 'Drinks', planned: 20000, actual: 0 },
  ],
  dedicationLogistics: [
    { item: 'Thanksgiving Fund', planned: 200000, actual: 0 },
    { item: 'Programs (200 Copies)', planned: 200000, actual: 0 },
    { item: 'Instruments (Sound, Mic)', planned: 100000, actual: 0 },
    { item: 'Fuel 110 Liters @ 1,000', planned: 110000, actual: 0 },
    { item: 'Banners (2)', planned: 40000, actual: 0 },
    { item: 'Ink for Printer', planned: 10000, actual: 12000 },
    { item: 'Logistics (Transport)', planned: 100000, actual: 0 },
    { item: 'Fruits', planned: 100000, actual: 0 },
    { item: 'Decoration', planned: 100000, actual: 0 },
    { item: 'Cake', planned: 50000, actual: 0 },
    { item: 'Ballons & Ribbons', planned: 20000, actual: 0 },
    { item: 'Chairs and Canopy', planned: 30000, actual: 0 },
    { item: 'Towels (2 Dozens)', planned: 22500, actual: 21500 },
    { item: 'Small Card Envelops (50 Copies)', planned: 15000, actual: 15000 },
    {
      item: 'Small Normal Envelops (300 Copies)',
      planned: 25000,
      actual: 25000,
    },
    { item: 'ATM Card (Committee Account)', planned: 2500, actual: 2500 },
    // { item: 'CAC Registration', planned: 19000, actual: 19000 },
    {
      item: 'Correction on Envelop',
      planned: 6000,
      actual: 0,
      note: 'Refund by church',
    },
    { item: 'Receipt', planned: 12000, actual: 12000 },
    { item: 'Printing on Towel (2 Dozens)', planned: 3000, actual: 3000 },
    { item: 'Invitation to King', planned: 10500, actual: 10500 },
    { item: 'Invitation to Bale Lafenwa', planned: 3500, actual: 3500 },
  ],
  dedicationEntertainment: [
    { item: 'Cow (2)', planned: 1500000, actual: 0 },
    {
      item: 'Rice (3 Bags)',
      planned: 240000,
      actual: 30000,
      note: 'Half bag of rice in store',
    },
    { item: 'Bottle Water (50 Packs)', planned: 65000, actual: 0 },
    { item: 'Small Soft Drinks (17 Packs)', planned: 48000, actual: 0 },
    { item: 'Big Soft Drinks (50 Packs)', planned: 210000, actual: 0 },
    { item: 'Pepper & Onions', planned: 200000, actual: 0 },
    { item: 'Groundnut Oil (25L x 2)', planned: 120000, actual: 0 },
    { item: 'Tin Tomatoes x 4 @ 15,000', planned: 60000, actual: 0 },
    { item: 'Takeaway Packs', planned: 150000, actual: 0 },
    { item: 'Gas (12kg Cylinders x 3)', planned: 43500, actual: 0 },
    { item: 'Bay Leaf', planned: 2000, actual: 0 },
    { item: 'Gas Burner', planned: 5000, actual: 0 },
    { item: 'Cooking Pot (Large x 3)', planned: 10000, actual: 0 },
    {
      item: 'Takeaway Packs for Guest of Honour (100 pcs)',
      planned: 150000,
      actual: 0,
    },
    { item: 'Semo 20kg', planned: 34000, actual: 0 },
    { item: 'Vegetables & Ewedu', planned: 7000, actual: 0 },
  ],
};
