export const incomeData: IncomeData = {
  harvestCommittee: [
    { name: 'Bro Taiwo Babarinde', amount: 519000 },
    { name: 'Mummy Oluwunmi', amount: 250000 },
    { name: 'Pst Mrs V.A Adeyemo', amount: 70000 },
    { name: 'Sis Motunrayo Adelani', amount: 50000 },
    { name: 'Bro Alaba Adeyi', amount: 40000 },
    { name: 'Bro Festus Kayode', amount: 30000 },
    { name: 'Sis Oluwakemi Shehu', amount: 30000 },
    { name: 'Sis Sarah Adebayo', amount: 22000 },
    { name: 'Evang Bunmi Emmanuel', amount: 21500 },
    { name: 'Sis Omolola Samaiye', amount: 21000 },
    { name: 'Sis Grace Adekunle', amount: 20000 },
    { name: 'Bro Olusola Olaseni', amount: 17000 },
    { name: 'Sis Dayo Olubukonla', amount: 15000 },
    { name: 'M/S/A Gidigbi', amount: 15000 },
    { name: 'Sis Bolanle Ajayi', amount: 10000 },
  ],
  sponsors: [
    { name: 'Pro Kehinde Ogunleti Envelop 4', amount: 54200 },
    { name: 'Mr Taiwo Oshodi', amount: 50000 },
    { name: 'Mr Oluwatobi Emmanuel', amount: 40000 },
    { name: 'Pro Kehinde Ogunleti Envelop 3', amount: 47000 },
    { name: 'Pro Kehinde Ogunleti Envelop 2', amount: 40600 },
    { name: 'Praise Night', amount: 19800 },
    { name: 'Church Members Envelop 1', amount: 17400 },
    { name: 'Pro Kehinde Ogunleti Envelop 1', amount: 13800 },
    { name: 'Mama Dangote Full Page Ads', amount: 10000 },
    { name: 'Grandma Ogunleti', amount: 10000 },
    { name: 'Easter Band Ads', amount: 5000 },
    { name: 'Choir Band Ads', amount: 5000 },
    { name: 'Mary Band Ads', amount: 5000 },
    { name: 'Mr Yusuf Abdulateef', amount: 5000 },
    { name: 'Alhaji Abiodun', amount: 5000 },
    { name: 'M/I/I Ogunleti Envelop 1', amount: 3500 },
  ],
  adultContributions: [
    { name: 'Mrs Ebenzer', amount: 15000 },
    { name: 'Sis Sarah Babarinde', amount: 15000 },
    { name: 'Sis Justina Ayeni', amount: 15000 },
    { name: 'Sis Victoria Funmilayo', amount: 15000 },
    { name: 'Bro Paul Olarenwaju Oyekan', amount: 15000 },
    { name: 'Sis Shola Oriyomi', amount: 15000 },
    { name: 'Sis Oluwatoyin Adekunle', amount: 15000 },
    { name: 'Sis Oluwatoyin Edunjobi', amount: 15000 },
    { name: 'Sis Ayomide Ajaga', amount: 15000 },
    { name: 'Sis Funke Oyetunde', amount: 15000 },
    { name: 'Sis Olabisi Akinlalu', amount: 15000 },
    { name: 'Sis Adedoyin Ogungbesan', amount: 15000 },
    { name: 'Sis Ayomide Olowo', amount: 15000 },
    { name: 'Sis Atinuke Adegunle', amount: 15000 },
    { name: 'Sis Sholesi Ajoke', amount: 15000 },
    { name: 'Sis Adedeji', amount: 15000 },
    { name: 'Sis Ajose', amount: 13000 },
    { name: 'Sis Okegbemi Yemisi', amount: 13000 },
    { name: 'Mrs Ifeoluwa Amusa', amount: 10000 },
    { name: 'Sis Peter Oluwayemisi', amount: 10000 },
    { name: 'Sis Prayer Ifadah', amount: 10000 },
    { name: 'Sis Festus Kayode', amount: 10000 },
    { name: 'Sis Moshood', amount: 10000 },
    { name: 'Sis Kehinde Adegbaye', amount: 5000 },
    { name: 'Mrs Balogun', amount: 5000 },
    { name: 'Mama Eleedu', amount: 5000 },
    { name: 'Visitor', amount: 5000 },
    { name: 'Bro Isaac Adeolu', amount: 5000 },
    { name: 'Sis Osewunmi Adeolu', amount: 5000 },
  ],
  childrenChairPersons: [
    { name: 'Oluwadamilola Ganiyat', amount: 20000 },
    { name: 'Master David Agbonrofo', amount: 10000 },
    { name: 'Miss Bernice Babarinde', amount: 10000 },
    { name: 'Miss Eunice Babarinde', amount: 10000 },
    { name: 'Master Samuel Bankole', amount: 10000 },
    { name: 'Miss Gbebemi Ogunleti', amount: 10000 },
    { name: 'Miss Aderemi Temitope Sarah', amount: 10000 },
    { name: 'Miss Ifada Emmanuela', amount: 10000 },
    { name: 'Miss Modupeola Ajaga', amount: 10000 },
    { name: 'Miss Oluwanifemi Babajide', amount: 10000 },
    { name: 'Master Micheal Oriyomi', amount: 10000 },
    { name: 'Master Ireoluwa Akintunde', amount: 10000 },
    { name: 'Master Okegbemi Ademide', amount: 10000 },
    { name: 'Miss Peculiar Williams', amount: 10000 },
    { name: 'Miss Ogooluwa Ogunsakin', amount: 10000 },
    { name: 'Elder Bro Olusola Olaseni', amount: 2000 },
  ],
  childrenMembers: [
    { name: 'Master Daniel Sholesi', amount: 3000 },
    { name: 'Miss Darasimi Sholesi', amount: 3000 },
    { name: 'Miss Easter Sholesi', amount: 3000 },
    { name: 'Sis Abimbola Adedeji', amount: 3000 },
    { name: 'Sis Abimbola Adedeji', amount: 3000 },
    { name: 'Master Temitope Amusa', amount: 3000 },
    { name: 'Sis Anabel Damilola', amount: 3000 },
    { name: 'Master Juwon Ayeni', amount: 3000 },
    { name: 'Sis Ayeni Justina', amount: 1000 },
    { name: 'Master Ogo Omogiade', amount: 3000 },
    { name: 'Miss Hephzibah Omogiade', amount: 3000 },
    { name: 'Korede Edunjobi', amount: 3000 },
    { name: 'Mrs Ebenezer', amount: 3000 },
    { name: 'Mrs Ebenezer', amount: 3000 },
    { name: 'Mrs Ebenezer', amount: 3000 },
    { name: 'Master Damilare Adekunle', amount: 3000 },
    { name: 'Master Damilola Adekunle', amount: 3000 },
    { name: 'Fasia Adekunle', amount: 3000 },
    { name: 'Sis Tunji Olawale', amount: 3000 },
    { name: 'Sis Tobi Olawale', amount: 3000 },
    { name: 'Sis Tobi Olawale', amount: 3000 },
    { name: 'Mrs Akinlatu', amount: 3000 },
    { name: 'Miss Deborah Ogungbesan', amount: 3000 },
    { name: 'Master Enoch Ogungbesan', amount: 3000 },
    { name: 'Miss Kemi Amosu', amount: 3000 },
    { name: 'Olayinka Emmanuel Shobiyi', amount: 3000 },
    { name: 'Miss Gbotemi Ogunleti', amount: 3000 },
    { name: 'Miss Nifemi Ogunleti', amount: 3000 },
    { name: 'Bro Alaba Adeyi', amount: 3000 },
    { name: 'Master Gabriel Okesina', amount: 3000 },
    { name: 'Master Okiki Alaba', amount: 3000 },
    { name: 'Miss Ifeoluwa Alaba', amount: 3000 },
    { name: 'Isreal Sambo', amount: 3000 },
    { name: 'Master Oni Micheal', amount: 3000 },
    { name: 'Miss Kehinde Oyekan', amount: 3000 },
    { name: 'Master Taiwo Oyekan', amount: 3000 },
    { name: 'Miss Darasimi Adeolu', amount: 3000 },
    { name: 'Master Erioluwa Adeolu', amount: 3000 },
    { name: 'Miss Eniola Amusa', amount: 0 },
  ],
  childrenHarvestDay: 26200,
  dedicationHarvestDay: 416000,
  childrenOutstanding: [
    { name: "Evang Bunmi Emmanuels's Family", amount: 20000 },
    { name: "Adeyemo's Family", amount: 13000 },
    { name: "Ayeni's Family", amount: 2000 },
  ],
};
