export const incomeData: IncomeData = {
  harvestCommittee: [
    { name: 'Bro Taiwo Babarinde', amount: 200000 },
    { name: 'Anonymous', amount: 70000 },
    { name: 'Mummy Oluwunmi', amount: 50000 },
    { name: 'Mama Dangote', amount: 50000 },
    { name: 'Evang Bunmi Emmanuel', amount: 20000 },
    { name: 'Sis Serah Adebayo', amount: 20000 },
    { name: 'Sis Aduni Adeyemi', amount: 5000 },
  ],
  sponsors: [],
  adultContributions: [
    { name: 'Mrs Ebenzer', amount: 10000 },
    { name: 'Mrs Ifeoluwa Amusa', amount: 10000 },
    { name: 'Sis Sholesi Ajoke', amount: 4000 },
  ],
  childrenChairPersons: [
    { name: 'Oluwadamilola Ganiyat', amount: 20000 },
    { name: 'Master David Agbonrofo', amount: 10000 },
    { name: 'Miss Bernice Babarinde', amount: 10000 },
    { name: 'Miss Eunice Babarinde', amount: 10000 },
    { name: 'Master Samuel Bankole', amount: 10000 },
    { name: 'Miss Gbotemi Ogunleti', amount: 10000 },
    { name: 'Miss Aderemi Temitope Sarah', amount: 10000 },
    { name: 'Miss Ifada Emmanuela', amount: 10000 },
    { name: 'Miss Modupeola Ajaga', amount: 10000 },
    { name: 'Miss Oluwanifemi Babajide', amount: 10000 },
    { name: 'Master Micheal Oriyomi', amount: 10000 },
    { name: 'Master Ireoluwa Akintunde', amount: 10000 },
    { name: 'Master Okegbemi Ademide', amount: 10000 },
    { name: 'Miss Peculiar Williams', amount: 10000 },
    { name: 'Miss Ogooluwa Ogunsakin', amount: 8000 },
    { name: 'Elder Bro Olusola Olaseni', amount: 2000 },
  ],
  childrenMembers: [
    { name: 'Master Daniel Sholesi', amount: 3000 },
    { name: 'Miss Darasimi Sholesi', amount: 3000 },
    { name: 'Miss Easter Sholesi', amount: 3000 },
    { name: 'Sis Abimbola Adedeji', amount: 3000 },
    { name: 'Sis Abimbola Adedeji', amount: 3000 },
    { name: 'Master Temitope Amusa', amount: 3000 },
    { name: 'Sis Anabel Damilola', amount: 3000 },
    { name: 'Master Juwon Ayeni', amount: 3000 },
    { name: 'Sis Ayeni Justina', amount: 1000 },
    { name: 'Master Ogo Omogiade', amount: 3000 },
    { name: 'Miss Hephzibah Omogiade', amount: 3000 },
    { name: 'Korede Edunjobi', amount: 3000 },
    { name: 'Mrs Ebenezer', amount: 3000 },
    { name: 'Mrs Ebenezer', amount: 3000 },
    { name: 'Mrs Ebenezer', amount: 3000 },
    { name: 'Master Damilare Adekunle', amount: 3000 },
    { name: 'Master Damilola Adekunle', amount: 3000 },
    { name: 'Fasia Adekunle', amount: 3000 },
    { name: 'Sis Tunji Olawale', amount: 3000 },
    { name: 'Sis Tobi Olawale', amount: 3000 },
    { name: 'Sis Tobi Olawale', amount: 3000 },
    { name: 'Mrs Akinlatu', amount: 3000 },
    { name: 'Miss Deborah Ogungbesan', amount: 3000 },
    { name: 'Master Enoch Ogungbesan', amount: 3000 },
    { name: 'Miss Kemi Amosu', amount: 3000 },
    { name: 'Olayinka Emmanuel Shobiyi', amount: 3000 },
    { name: 'Miss Gbebemi Ogunleti', amount: 3000 },
    { name: 'Miss Nifemi Ogunleti', amount: 3000 },
    { name: 'Bro Alaba Adeyi', amount: 3000 },
    { name: 'Master Gabriel Okesina', amount: 3000 },
    { name: 'Master Okiki Alaba', amount: 3000 },
    { name: 'Miss Ifeoluwa Alaba', amount: 3000 },
    { name: 'Isreal Sambo', amount: 3000 },
    { name: 'Master Oni Micheal', amount: 3000 },
    { name: 'Miss Kehinde Oyekan', amount: 3000 },
    { name: 'Master Taiwo Oyekan', amount: 3000 },
    { name: 'Miss Eniola Amusa', amount: 3000 },
    { name: 'Miss Darasimi Adeolu', amount: 3000 },
    { name: 'Master Erioluwa Adeolu', amount: 3000 },
  ],
  childrenHarvestDay: 26200,
  childrenOutstanding: [
    { name: "Babarinde's Family", amount: 10000 },
    { name: "Adeyemo's Family", amount: 3000 },
    { name: "Ayeni's Family", amount: 2000 },
    { name: "Ogunsakin's Family", amount: 2000 },
  ],
};
